### ISSUE TITLE
Implementers R Us: quick wins allowing rapid-fire installation by almost anyone

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1028]
Implementers want uninterrupted installs (or at the very least, as streamlined and as rapid as possible).

Here are just a few such related issues &mdash; to unlock WYSIWIG rapid provisioning of Internet-in-a-Box's &mdash; across entirely new demographics in 2019:

- [x] #317, #1141 Install OpenVPN/TeamViewer/support tool(s) BEFORE installs begin [or near the very beginning!]
  - [x] PRs #996, #997, #998, #1000, #1001, #1003, #1004 making the [openvpn playbook/role](https://github.com/iiab/iiab/tree/master/roles/openvpn) more readable, while implementing variable openvpn_handle
  - [ ] #1124 Consider OpenL2TP or xl2tpd as an alternative to OpenVPN ?
- [x] #796 Rapid networking & other IIAB config changes that can't wait ~20min for Ansible
- [ ] #799 #1041 Standardize upgrade/reinstall of IIAB services (server apps)
- [x] #872 Reboot + Auto-Continue...IIAB Install Scripts (for OS updates etc)
- [x] #880 "Install script fails to create /opt/iiab/downloads folder"
- [x] #884 "Automate torrenting+installing of KA Lite videos in 7 languages"
- [ ] #923 Failing URL's—parent tkt to consolidate diverse issues 
- [x] #958 Non-ASCII Characters in install.txt Bash Script
- [x] #963, https://github.com/iiab/iiab-factory/pull/33 Host install.txt on Github
- [x] #994 Should IIAB support NOOBS to broaden participation? [too expensive]
- [x] #977 Kolibri 0.10.2+ Release Polish
  - [ ] #1545 Kolibri Bug Scrub for IIAB 7.0+
- [x] #1147 PRs #1161 #1165 #1166 #1288 Support high-traffic usage of WordPress and/or Moodle, by toggling "apache_high_php_limits"
  - [x] #1287 Duplicating WordPress using "All-in-One WP Migration" plugin: does http://FAQ.IIAB.IO (“WordPress & Moodle Administration: What tips & tricks exist?”) describe this sufficiently?
- [x] #1130 Remove Ansible's pink/red warnings. Prep for Ansible 2.8/2.9 and 2.11
- [x] #1160 Proactively discourage pi/raspberry password compromises
- [ ] #1182 Captive Portal improvements needed
- [x] #1189 Install Script: prompt to set iiab-admin password
- [ ] #1200 Roles missing READMEs
- [x] #1232 Housekeeping: Remove deprecated files and unused scripts
- [x] #1386 Fixes for 2019's Debian 10 "Buster" + 2 outstanding issues incl workarounds
  - [x] #1387 Debian 10 Buster: 2 outstanding issues w/ workarounds + 1 bug (Kolibri)
- [x] Refine table @ http://FAQ.IIAB.IO item 9: _"What services (IIAB apps) are suggested during installation?"_
- #1536 IIAB installer should make hotspot & networking choices far more understandable
- [x] #1575 PR #1596 `iiab-diagnostics` reporting command
  - [x] #1700 Install pkg pastebinit on all IIAB's
- [x] PR #1654 Making OpenVPN far easier to install, start & understand
- [ ] #1656 --non-interactive flag for "sudo iiab" installer
- [x] #1664 PRs #1665 #1677 #1691 #1692 #1693 Firewall "knob/dial" so new implementers understand their Main Options with iptables
- [ ] #1708 Understanding IIAB's Admin Console ([box.lan/admin](http://box.lan/admin)) > Content Menus (tab)
- [x] #1710 Living Docs for IIAB 7.0 Maps

**Comment by jvonau** [comment]
#1656 iiab/iiab-factory#134

**Comment by jvonau** [comment]
Are we(?) there yet?

**Comment by holta** [comment]
> Are we(?) there yet?

Absolutely huge progress since 3 year ago in August 2018, for sure!

But "I want what she has" rapid-fire installation of Learning Bouquets is the next step &mdash; to properly de-bureaucratize.

So the spirit of open learning is not all talk.  But brings "explosive" grassroots action/traction to highly motivated but much-lesser-skilled folk in every country.

**Comment by jvonau** [comment]
stale

**Comment by holta** [comment]
> stale

And yet ever-present, very real challenges...

**Comment by jvonau** [comment]
Yet the single most annoying issue is the forced reboot to cover if RasPiOS's kernel was updated when apt upgrade is ran. Simple solution I mentioned years ago, run apt upgrade last in 'iiab'. Still prime the cache with apt update but should any new package installs require the newest packages of those already installed those will get pulled in anyway. Once iiab/admin are installed what packages that have not been updated will get picked up, nothing really changing other than the kernel might get updated last before the final reboot question. The RasPiOS running kernel/on disk issue is avoided till the very end, but the check for that situation could occur sooner. Might grant the wish of curl to end with no rebooting. https://github.com/iiab/iiab/issues/2975#issuecomment-911998804
