### ISSUE TITLE
Captive Portal improvements checklist

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1182]
Building on #412 #608 PRs #870 #1179 #1180 towards a Captive Portal understandable by almost all:

- [x] http://iiab-server.lan/home/ is not acceptable in the field; it needs to show http://box/* or http://box.lan/* per custom setting in [local_vars.yml](http://wiki.laptop.org/go/IIAB/local_vars.yml)
- [ ] Intermediary splash page needs:
  - [ ] #1784 UX: Captive Portal: The title/text of the page is not centered on the screen
  - [ ] Larger fonts
  - [ ] Very crisp/concise/colorful instructions in the most simple English possible _(for non-native speakers; ALL users want this disruptive interface minimized!)_
  - [ ] Implement auto-redirect from intermediary splash page after 10-seconds, per @tim-moody's recommendation, ideally with Javascript countdown (1 in ~10 users want to read instructions)
- [ ] #224 NGINX alongside Apache for better analytics (& Captive Portal too?)
- [x] #608 Captive Portal experimental support summary in http://FAQ.IIAB.IO ?
- [x] Remove bugs associated with transition from named/BIND to dnsmasq
  - [x] #1184 PR #1185
  - [x] PR #1197 Delete roles/1-prep/templates/.iiab.env.j2.un~
  - [x] de-emphasize named/BIND in future? (effectively de-supporting Ubuntu 16.04)
  - [x] #1249 Clarify `block_DNS` & `dns_jail_enabled` in default_vars.yml & local_vars.yml
  - [x] https://github.com/iiab/iiab/pull/1207#issuecomment-428611396 -> #1250 dhcp_service & dhcp_service2 in network/tasks (revise &/or remove from network/defaults ?)
- [x] hostapd failed to start even on reboot of RPi 3 B+ (manual restart of service worked, this resulted from installing IIAB over Wi-Fi, and needing to run iiab-hotspot-on after IIAB's install completed!)
- [x] PR #1311 Consider including some of the best of @jvonau's staging ideas?  (What's best for code maintenance/understandability?)
- [x] PR #1364 dnsmasq hack (in roles/captive-portal/tasks/main.yml) so iiab-install runs on Ubuntu 16.04
- [ ] Windows generally working?
  - [ ] Windows 7 & 8.1 need to work (a browser tab is opened to go.microsoft.com sometimes redirecting to https://www.msn.com/... as detailed in PR #1180, but Captive Portal does not yet work on these platforms)
    - [x] PR #1180 py-captive-portal - finishing touches on PR #1179
  - [x] #1351 Captive Portal fails with Windows 8.1 & Windows 10
- [ ] Android generally working?
  - [x] Android 8 does not work for @tim-moody on [2018-10-23](https://github.com/iiab/iiab/issues/1182#issuecomment-432728079)
  - [x] Android 7 does not work for @tim-moody on [2018-10-24](https://github.com/iiab/iiab/issues/1182#issuecomment-432728079) (Android 7.0 does work for others)
  - [ ] #1323 Captive Portal fails with Android 8, 8.1 & 9 (but Android 9 Pixel XL works!)
    - [x] #1363 Captive Portal: patch capture-wsgi.py to test Android 7.x, 8.x, 9.x
    - [ ] #1376 Captive Portal w/ Android 7.x & 8.x should not require you to click "Connected, no Internet" / "Stay connected"
- [ ] #1366 Captive Portal fails when IIAB installed on Ubuntu 18.04?  (And 16.04 too, in case that informs?)
  - [ ] Browser sometimes hangs at blank page http://connectivitycheck.gstatic.com/generate_204 after https://captive.lan/android_splash e.g. when connecting Android 7 to Ubuntu 18.04 (on 1st attempt only?)
- [x] @jvonau asks on 2018-10-23: 'Wondering what the purpose of "catch" is... "uncatch" populates from urllist and is called in the playbook... But has redundant calls that are dup'd in the playbook...'  [@georgejhunt clarifies on 2018-10-25: "catch" attempts to discover URL's used by unknown devices...is supposed to add to list of known URL's...but does not yet work, dead code for now by might again by useful for Tim etc?  "uncatch" turns off Apache.]
- [x] Move [roles/network/tasks/captive_portal.yml](https://github.com/iiab/iiab/blob/master/roles/network/tasks/captive_portal.yml) to roles/py-captive-portal or roles/captive-portal ?
- [ ] #1418 Captive portal test matrix
- [x] #1469 dnsmasq fails often in captive-portal / 4-server-options on multiple OS's
- [ ] #1504 "Captive Portal doesn't work if Ethernet cable removed" [TK Kang report]
- [ ] _We need to work to cultivate bug reports, otherwise this will never work!_  Help us improve our http://FAQ.IIAB.IO outreach documentation here: http://wiki.laptop.org/go/IIAB/FAQ#Captive_Portal_Administration:_What_tips_.26_tricks_exist.3F
- [x] #1510 iiab-banner6.png moved [Captive Portal fix]
- [x] #1518 Captive Portal: works on Windows 7,8,10, with no network wire
- [ ] #1562 Don't hard code captive_portal url
- [ ] https://github.com/iiab/iiab/issues/1810#issuecomment-548020264 Transition to Python 3 version of mod_wsgi
- [ ] Captive Portal should [act upon](https://github.com/iiab/iiab/issues/1182#issuecomment-547430831) /etc/iiab/local_vars.yml variable `iiab_home_url: /wordpress` or `iiab_home_url: /nextcloud` when implementer has changed this from `iiab_home_url: /home`
- [ ] #2022 "Apache warnings [never-matching / duplicate Alias directives]" and likewise /var/log/apache2/portal.log contains many Python errors.  Reported by @tim-moody 2018-10-23.
- [x] PR #2070 Cap3.1 on NGINX and Python 3 [Captive Portal]
- [x] PRs #2171 #2185 uWSGI fix for NGINX & Captive Portal (Admin Console too?)
- [ ] #2172 Does IIAB's Captive Portal work on Ubuntu? Debian?

**Comment by tim-moody** [comment]
Tests:
Tests S9+ Android 8
•	connect to IIAB ssid
•	takes awhile
•	says internet may not be available
•	did not get splash page
•	did not get redirected

Tests S6 Android 7
•	No security on ssid
•	Connected to ssid
•	Got splash screen  with SIGN IN TO WI-FI NETWORK
•	Two links:
•	Click first to get browser we need
•	Then click to go to home page
•	I clicked first
•	I get ssl cert not trusted
•	Refreshes but looks like same page with SIGN IN message and two links
•	Clicked second link
•	Took me to wifi page and now says Internet in a Box with status connected
•	But didn’t take me to home page
•	Took an internet link and does not reach it
•	Put box.lan in url
•	It tries to search
Cleared chrome cache and tried again
•	Connected
•	Signin message popped up briefly then when to another ssid
•	Clicked second link without first and got same as above after ‘clicked second’
•	Never get to home page
•	Now I get internet may not be available messages
Reboot for one last try
•	Still just get message about internet may not be available
•	Forget network
•	Now get splash
•	Click first link
•	I get ssl cert not trusted
•	Refreshes but looks like same page with SIGN IN and two links
•	Clicked second link
•	Back to wifi screen but says signed in
•	Never got to home page

**Comment by georgejhunt** [comment]
Tim,
Reading through the log that you sent to me, I see stuff that I've never seen before. 
Would you try the following:
"unlink /etc/apache2/sites-enabled/captive-portal.conf"
"ln -sf /etc/apache2/sites-available/captive-portal.conf /etc/apache2/sites-enabled/001-captive-portal.conf"
and then "systemctl restart apache2"

I think I was confused about apache config file precedence, but I need apache2 to handle the hosts that are not in my target list of urls (and the last <virtual_host *:80> seems to win.

**Comment by tim-moody** [comment]
I tried the above with no change in how Android 7 on Galaxy S6 behaves.

**Comment by tim-moody** [comment]
OK missed "unlink /etc/apache2/sites-enabled/captive-portal.conf"

**Comment by georgejhunt** [comment]
I've commented out the put_204 for android, and made the default response be 404. I left the capture server running with the -l flag inside of a screen instance. Can you try it again? Thanks

**Comment by tim-moody** [comment]
Another test of S9+ android 8
•	Connected to ssid
•	Splash popped up
•	Clicked top link
•	Got same page still with SIGN IN TO WIFI
•	Clicked bottom link
•	Went to home page but still has SIGN IN TO WIFI
•	In vertical ellipsis menu there is an 'open in browser' option on each of the SIGN IN TO WIFI screens
•	Clicking it takes me to splash, but I think I now have chrome as the ellipsis menu has a full set of options
•	Now if I take the second link I get to the home page **without** SIGN IN TO WIFI

This suggests to me that there is no value in sending me to the splash page. You could just send me to the home page and I could use the 'open in browser' option to get a real browser

**Comment by georgejhunt** [comment]
Are you thinking that we would change the home page to instruct the user to
click on the ellipsis, and click on the "open in Browser" for all
platforms? How would that work?

**Comment by holta** [comment]
@georgejhunt working on this new branch containing improvements for Android 7 / 8 and Windows 7:

https://github.com/georgejhunt/iiab/tree/cap1

**Comment by georgejhunt** [comment]
On a new install of captive-portal, after it was pulled into master, I discovered a dependency on cmd-srv in iiab-admin-console. Because of the order one must do the install, this dependency is not met until iiab-admin-console is installed.
It will require a reboot, before the captive portal functions. 
One option would be to move iiab_env.py back into IIAB.

**Comment by tim-moody** [comment]
don't think iiab_env.py is part of iiab-admin-console

https://github.com/iiab/iiab/blob/84da40c40d6f1b7d27249e2f8ca2b3614c66c346/roles/4-server-options/tasks/main.yml

**Comment by georgejhunt** [comment]
You're right. It was down in 4_server_options below captive portal. So I
did a PR to put it in 3-base-server

**Comment by holta** [comment]
fyi PR #1327 has been merged, containing @georgejhunt's latest Captive Portal ("cap3") as part of Apache.

**Comment by holta** [comment]
@georgejhunt: at least 7 of 22 items are now complete on the above checklist.

(Please advise on how we should tidy up Captive Portal for IIAB 6.7's final release in coming days, so testers in all countries report back the most useful data for us in coming weeks!)

**Comment by holta** [comment]
@georgejhunt & @jvonau can you confirm merged PR https://github.com/iiab/iiab/pull/1379 is sufficient to resolve the top issue on our Captive Portal checklist above?

(http://iiab-server.lan/home/ is not acceptable in the field; it needs to show http://box/* or http://box.lan/* per custom setting in local_vars.yml)

**Comment by holta** [comment]
Is the strategy outlined at http://community.rachelfriends.org/t/captive-portal/1387 promising?

**Comment by ericnitschke** [comment]
Hi @georgejhunt. Is it currently possible to choose where the captive portal defaults to? Would prefer box.lan/wordpress over box.lan/home if possible.  Have edited local_vars.yml to default to WP instead of Home upon typing box.lan, but the captive portal still goes to Home.

**Comment by holta** [comment]
> Hi @georgejhunt. Is it currently possible to choose where the captive portal defaults to? Would prefer box.lan/wordpress over box.lan/home if possible. Have edited local_vars.yml to default to WP instead of Home upon typing box.lan, but the captive portal still goes to Home.

Excellent Question, thanks @ericnitschke.

ASIDE: please also see the latest Captive Portal glitches on (many but not all) Android 8's and Android 9's, such that you can hopefully confirm the latest with reports of your own:

#1885 IIAB's Captive Portal can be extremely frustrating on recent versions of Android

(In short, not all was resolved here for [IIAB 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes), but we are hopeful that IIAB 7.1 will do a better job with Android 8/9 and the new Android 10 "being released this month August 2019" hopefully too!)

**Comment by tim-moody** [comment]
@ericnitschke I think the answer is in https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py. Perhaps should go to / rather than /home and then picks up the defined default for home page.

**Comment by holta** [comment]
> @ericnitschke I think the answer is in https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py. Perhaps should go to / rather than /home and then picks up the defined default for home page.

`/home` is hard-coded in 4 places here:

- https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L188
- https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L198
- https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L218
- https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L375

@georgejhunt  can you confirm these are the places it needs to be changed and/or recommend a strategy?

**Comment by georgejhunt** [comment]
I notice that FQDN is being passed to jinja2 ./files/simple.template at
line 232 of capture_wsgi.py.

In simple.template, line 72, FQDN is the href target. So I think that it is
also necessary to set ./vars/default_vars.yml line 71 to "iiab_home_url:
/wordpress".  Maybe you have already done that. (But this would only impact
function on android clients. You should probably focus on the clients you
expect).

We definitely need a better strategy. The captive_portal code is an
evolution of trial and error, for all the different clients. I've never
found a "one-size fits all" solution.

In the trial and error approach, a change for one client can break function
for another client. I found it very frustrating and difficult.

I'm hoping that someone else will pick up the ball, and find a better
solution for our next release.

**Comment by georgejhunt** [comment]
And I should have suggested that iiab_home_url be changed in
/etc/iiab/local_vars.yml, so that updates to iiab do not overwrite

**Comment by ericnitschke** [comment]
I'm going to prepare a demo box to run all week during [Internet Governance Forum](https://igf2019.intgovforum.org) in Berlin (Nov 25 -29).  I'll make an explanatory splash page at /wordpress, as done with the box I made for the eLearning Africa conference.

Any ideas for temporary solutions to get the Captive Portal to go straight to /wordpress?

**Comment by holta** [comment]
> I'm going to prepare a demo box to run all week during [Internet Governance Forum](https://igf2019.intgovforum.org) in Berlin (Nov 25 -29). I'll make an explanatory splash page at /wordpress, as done with the box I made for the eLearning Africa conference.
> 
> Any ideas for temporary solutions to get the Captive Portal to go straight to /wordpress?

@georgejhunt please help telling us which of the following @ericnitschke should set?

[/opt/iiab/iiab/roles/captive-portal/files/simple.template#L72-L73](https://github.com/iiab/iiab/blob/master/roles/captive-portal/files/simple.template#L72-L73) shows:
```
window.open("http://{{ FQDN }}","_system");
$.ajax("/home_selected");
```

[/opt/iiab/iiab/roles/captive-portal/templates/capture-wsgi.py#L188](https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L188 ) shows:
```
response_headers = [('Location','http://box.lan/home'),
```

[/opt/iiab/iiab/roles/captive-portal/templates/capture-wsgi.py#L198](https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L198) shows:
```
response_headers = [('Location','http://' + fully_qualified_domain_name + '/home'),
```

[/opt/iiab/iiab/roles/captive-portal/templates/capture-wsgi.py#218](https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L218) shows:
```
location = "http://" + fully_qualified_domain_name + "/home"
```

[/opt/iiab/iiab/roles/captive-portal/templates/capture-wsgi.py#L375](https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L375) shows:
```
location = "http://" + fully_qualified_domain_name + "/home"
```

[/opt/iiab/iiab/roles/captive-portal/templates/capture-wsgi.py#L469](https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L469) shows:
```
if  environ['PATH_INFO'] == "/home_selected":
```

_@ericnitschke of course follow the instructions to (re)install Captive Portal at http://FAQ.IIAB.IO Item 38 ("Captive Portal Administration: What tips & tricks exist?") after you've made any modifications within /opt/iiab/iiab/roles/captive-portal !_

**Comment by holta** [comment]
@georgejhunt since this is a repeated/ongoing request (@ericnitschke isn't the only person who's asked for this) can we make Captive Portal act upon [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F)'s customized home page URL `iiab_home_url: /wordpress` for example?

(The default is `iiab_home_url: /home` as seen in [local_vars_medium.yml#L32-L33](https://github.com/iiab/iiab/blob/master/vars/local_vars_medium.yml#L32-L33), that operators/implementers are asked to customize, as explained therein.)

**Comment by georgejhunt** [comment]
If we are going to soft code the captive portal target, perhaps we should
use all this information in local_vars.yml:
iiab_hostname: box
  iiab_domain: lan
  # Homepage: set to /home or /wordpress or /mediawiki or /wiki (for
DokuWiki)
  iiab_home_url: /home

We already have a path for getting ansible variables into python:

   1. We write the ansible variable into iiab.env -->
   https://github.com/iiab/iiab/blob/master/roles/1-prep/templates/iiab.env.j2
   2. And then we read the value with a python program which targets
   iiab.env =
   https://github.com/iiab/iiab/blob/master/roles/1-prep/templates/iiab_env.py.j2
   3. This seems like the time to migrate to python 3

I propose to re-use this mechanism.

**Comment by tim-moody** [comment]
why can cap portal not direct to / which is already configured elsewhere to do the right thing?

**Comment by tim-moody** [comment]
python3 is a separate topic, but I would like to put all lib type code in
/usr/lib/python3/dist-packages/iiab/
there would be a file iiab_lib.py which would contain what is currently in iiab_env.py and other renusable python defs
there would also be adm_lib.py if adm cons is installed

**Comment by georgejhunt** [comment]
I think captive portal can proxy to /. And in the short term maybe that is
enough.

Seems fine to put iiab lib in dist-packages.

**Comment by holta** [comment]
@georgejhunt has been poking at this today to see what's possible with Python 3, and proxying to / (to see if that's the best way to act upon the `iiab_home_url` variable?)

Not at all easy, despite what others around the planet perpetually claim (:

Profound thanks George!

**Comment by holta** [comment]
FYI on #1810 @tim-moody writes:

> mod_wsgi for apache can only be python 2 OR 3, not both. it is used by
captive portal
cmdsrv
pathagar

**Comment by ericnitschke** [comment]
cross-posted on Skype: 

Thanks [ @georgejhunt ] & [ @holta ] for the captive portal help.  Just did a big-size install on an RPi4 4GB with a 256 card.  Hit the kernel issue Adam warned about, resolved by rpi-update and a restart.  I enabled the portal and changed homepage to /wordpress in local_vars.yml.  Got the initial landing page with 2 buttons (the page was slightly off center). 

First button had me choose between chrome and FF.  Second button went straight to /wordpress, which is great.

Then changed /home to /wordpress here:

    https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L188
    https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L198
    https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L218
    https://github.com/iiab/iiab/blob/master/roles/captive-portal/templates/capture-wsgi.py#L375

And ran
      cd /opt/iiab/iiab 
     ./runrole captive-portal 

No discernible changes to Captive Portal behavior.

**Comment by georgejhunt** [comment]
Eric. I'd like to get a captive portal set up to track your experiments.
I'll install wordpress, and captive portal on top of buster 9/26/2019 an
run it on rpi4. A lot of captive portal code depends on the client that
your are trying to manipulate -- by adjusting the client conversations.
What client are you working with? (hardware, OS, version)

**Comment by ericnitschke** [comment]
Thanks, George.  I was testing on an old Nexus 7 2013 tablet (android 6.0.1), which gave the above results.  Just tried again on a Motorola X4 (android 9) and the upon clicking the pop-up (Wifi has no internet access, Tap for options), Wordpress comes up, albeit not in the browser.  

Perhaps from there the wordpress landing page could have a link to direct users to the equivalent page within their browser of choice.

This is very promising! No more naming SSID: " Go to box.lan/wordpress for xyz...." :)

**Comment by georgejhunt** [comment]
In the general case, when an OS does not get back an expected "online
response" (different for each OS), the OS opens up what I think of as a
dumbed down limited browser.

There are lots of things that are disabled in that "walled garden".
Documentation is sparse. Trial and error has been my only solution that
works -- sometimes.

**Comment by holta** [comment]
@georgejhunt did you reach any conclusions trying to parametrize Captive Portal's destination site (e.g. http://box/home -> http://box/wordpress etc) last week?  What approach is likely best here?

ASIDE: what recommendations to you have towards migrating all of Captive Portal from Python 2.7 to Python 3?

**Comment by ericnitschke** [comment]
If the ethernet cable is plugged into the Pi, the captive portal landing page (and all navigation) takes about 2.5 minutes to load. 

With no cable the pages load immediately.

**Comment by holta** [comment]
> If the ethernet cable is plugged into the Pi, the captive portal landing page (and all navigation) takes about 2.5 minutes to load.
> 
> With no cable the pages load immediately.

TK Kang reported almost exactly the opposite:

#1504 "Captive Portal doesn't work if Ethernet cable removed" [TK Kang report]

Tangentially Related:

#926 TK: RPi WiFi hotspot can fail within an hour if Ethernet IS plugged in during boot?

**Comment by avni** [comment]
Just tested on the latest IIAB 7.1 pre-release on iOS 13.3, Android 8.1, and MacOS 10.2.6. 

1. Android 8.1 - improved, but still cannot see or bookmark the full URL. Connect to RPI's Wifi. Immediately the user gets a "Sign in to Wi-Fi network [SSID name]" notification at the top of the screen. Click it. A browser-like "sign-in to network" app immediately appears with the expected home page. If you then select the 3 dots in the upper right, you get a dropdown. From the dropdown, select "Use this network as is". The "sign-in to network" app and IIAB content page closes.  If user disconnects from network and reconnects, user gets the same experience. 
2. iOS 13.3 - First time connecting, captive portal shows up as expected. User can redirect to open IIAB in Safari. If user disconnects and reconnects, the captive portal does not show up. <strike>
3. MacOs 10.2.6 - Captive portal does not show up at all when connecting to network. <strike>

**Comment by avni** [comment]
Update: tested again on MacOS X 10.2.6 today and if I forget the Wifi SSID, Captive Portal does show up! So #3 in my previous comment is no longer valid.

**Comment by holta** [comment]
Thanks to @tim-moody & @ivanistheone:

> "CAPTIVE PORTAL:
The Definitive Guide
This is the most comprehensive guide to Captive Portal on the planet."
https://rootsh3ll.com/captive-portal-guide/

It may have a more up-to-date listing of "magic URL's" used by the latest browsers to detect whether they're online etc?

**Comment by holta** [comment]
Just FYI NoDogSplash (Captive Portal) has split into two projects:

1) NoDogSplash - stripped down and FAS removed to optimise for legacy devices with very restricted resources.

2) openNDS - containing the full FAS API for developing custom dynamic splash pages.  (FAS = Forward Authentication Service)

'As "no code" is the "smallest code", the simple Dnsmasq hack is the best way forward for NoDogSplash.'  [apparently targeting tiny devices like Raspberry Pi Zero]

https://github.com/openNDS/openNDS
