### ISSUE TITLE
Lokole (1) needs essential documentation (2) reply buttons should pre-populate "To" field

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1293]
Tracking ticket to keep us on track for Lokole as part of IIAB 6.7's release in December &mdash; many thanks to @aidan-fitz & @c-w for their ongoing help:

- [ ] PR #1305: Teachers need documentation (https://github.com/ascoderu/opwen-webapp/issues/81) building off @c-w's https://github.com/iiab/iiab/pull/1282#issuecomment-435704091 explaining how to:
  - [ ] Suspend & unsuspend accounts
  - [ ] Establish a superuser account to change others' passwords
  - [ ] Delegate such superuser privs to other users
  - [x] #1294 Change the right side of email address (currently appearing as USERNAME@iiab-box.lokole.ca)
    - [ ] https://github.com/iiab/iiab/pull/1294#issuecomment-439044880 How to wipe Lokole's database(s) clean, to freshly install a new version?  (With clean out-of-box settings if possible!)  e.g. `./runrole lokole` doesn't fix the right side of email addresses after PR #1294 merge.
- [x] Replying to email should pre-populate "To" field (https://github.com/ascoderu/opwen-webapp/issues/79)

Refs: https://github.com/iiab/iiab/pull/894 https://github.com/iiab/iiab/pull/1282#issuecomment-435622419

**Comment by veeara282** [comment]
@holta, think we're done with this issue now?

**Comment by holta** [comment]
> @holta, think we're done with this issue now?

If you think there's sufficient testing for now, yes.  The checklist above and the checklist at #1305 may be useful to spot-check future/evolving versions of Lokole, so perhaps bookmark 'em :)
