### ISSUE TITLE
Living Docs for IIAB 7.0 Maps [OSM]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1710]
A stream of questions and insights will arise for geographically-minded implementers as IIAB 7.0 Preview 1 is released in coming hours/days.

@mir123 & All: Let's keep these questions+answers organized in 1 public place, to ensure IIAB is listening to and responsive to its mappy users.

DRAFT Living Docs:

- NEW STUFF...
  - [x] Create https://github.com/iiab/iiab/wiki/IIAB-Maps
  - [x] What's new with IIAB 7.0 Maps?
    - [x] What might future versions bring?
    - [x] New IIAB installs show ["OpenStreetMap Test Page"](https://github.com/iiab/iiab/blob/master/roles/osm-vector-maps/templates/index.html) which should explain what implementers can do #1720
    - [x] How do I download & manage IIAB 7.0 Map Packs?  5 sub-questions about installing requirements, `/library/www/osm-vector-maps`, `regions.json`, `/usr/bin/iiab-update-map` @ https://github.com/iiab/iiab/issues/1612#issuecomment-497544317 & #1707
    - [ ] When should `/usr/bin/iiab-update-map` be used (e.g. for manual downloads) and what is it good for?
  - [x] PR #1724 Map redirect [OSM] ...may obviate the need for documentation!
  - [x] #1725 http://iiab.me/maps (or similar!) public demo site needed for latest/evolving IIAB 7.0 Maps
- ADVANCED TOPICS / REWORK THOSE DOCS WORTH SAVING... (which IIAB 6.6 & 6.7 maps docs & key points therein should be rescued/worked?  What IIAB 6.7 Maps docs / subsections should be marked as deprecated/archived?  Among...)
  - [x] "How do I add zoomable maps for my region?" @ http://FAQ.IIAB.IO (number 33 for now)
  - [x] Blurb @ top of https://github.com/iiab/maps ...what links are now best for map/tech-savvy community contributors?
    - [ ] Repo [README.md](https://github.com/iiab/maps/blob/master/docs/README.md) displayed @ bottom of https://github.com/iiab/maps
  - [ ] Legacy instructions for IIAB 6.6, "Offline OpenStreetMap + Regional Vector Map Datasets" : https://github.com/iiab/iiab-factory/blob/master/content/vector-tiles/README.md
  - [ ] Can I generate an IIAB Map Pack? DRAFT by @georgejhunt, that @mir123 might help with: https://github.com/georgejhunt/maps/blob/simple/generate-regions/readme.md

Refs:
#1704 Satellite tiles in z0-z9 package missing -- cause local blur
#1711 Vector Map double click unreliable

**Comment by holta** [comment]
Good Enough for IIAB 7.0, thanks @georgejhunt @mit123 & @tim-moody especially!

https://github.com/iiab/iiab/wiki/IIAB-Maps
