### ISSUE TITLE
Package up vector-based OSM maps

### ISSUE THREAD

**Issue by holta** [iiab/iiab#877]
@georgejhunt is working on this @ https://github.com/iiab/iiab-factory/pull/32

Related Demo Sites:
http://medbox.iiab.me/modules/en-osm-omt-min/ [shows STALE version, as of July/Aug 2018]
http://medbox.iiab.me/modules/en-osm-omt-central-am/ [shows STALE version, as of July/Aug 2018]

**Comment by holta** [comment]
- [x] Excellent progress as written up in DRAFT https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes
- [x] OSM instructions (implementer doc[s], not just low-level doc #1033, PR iiab/iiab-factory#39) need review with a fresh set of eyes, to see if a newbie installer can understand, follow, succeed!  Three summary docs listed at the bottom of http://download.iiab.io/content/OSM/vector-tiles/
- [x] #1035 Can OSM Vector Maps fill the entire screen?
- [x] #1034 How many cities are searchable by new Vector-based OSM?
- [x] #662 Teachers want Accents to work when searching for cities in OpenStreetMap (what's our status? who should assist?)
- [x] #1036 Keep OSM from zooming past Level 10, where there's no data?
- [ ] #1170 Haiti Diaspora Map Pack: aggregate street detail from 12+ global cities/regions
  - [x] iiab/iiab-factory#52 Merge non-overlapping .mbtiles regions (into single .mbtiles file)
- [x] #1192 Overcrowding of OSM map labels at Zoom Levels 13 and 14 (in cities)
- [ ] #1423 Regenerate OSM custom tilesets [incl hillshading & contours?]
- [x] Apply for HOTosm.org [microgrant](https://www.hotosm.org/projects/microgrants_and_community_development) ([2019 invitation](https://www.hotosm.org/updates/2019-hot-microgrants-program-empowering-local-openstreetmap-communities/)) to assist India/UX/packaging work especially?
- [x] #1496 Make http://box/maps & http://box/map work with whatever maps the implementer has...most recently installed?
- [ ] #1568 Magrit: Cartography Teaching+Learning as part of IIAB [with OSM?]
- [ ] Easily download any "continent" !
  - [x] PR #1600 Regional Vector Tile selection
  - [x] PR #1602 Explain osm_vector vars in {MIN, MEDIUM, BIG} local_vars.yml
  - [x] PR iiab/iiab-admin-console#160 Regional Tile selection Osmap2
  - [x] PR iiab/iiab-admin-console#161 Regional maps via vectors
  - [ ] #1605 New OSM Vector Maps need clean UX + clean instructions ("pick a continent or region") based on draft regions @ http://iiab.net/map <- http://iiab.net/osm-vector <- http://iiab.net/bboxes
    - [x] https://github.com/iiab/iiab-admin-console/pull/162 Display of 2 continents not poss: clarify confusing instructions
    - [x] iiab/maps#2 Shorter & more readable names for Downloadable Map Regions
    - [x] #1612 How can IIAB operators install the latest /library/www/osm-vector/maplist/assets/regions.json ? (catalog of downloadable maps, e.g. from d.iiab.io)
    - [x] #1619 Cleaner Admin Console "Continent Picker" to download & install OSM vector maps
    - [x] #1623 Cleanup of regions.json for IIAB 7.0 OSM "continents"
      - [x] #1704 Satellite tiles in z0-z9 package missing -- cause local blur
    - [x] #1710 Living Docs for IIAB 7.0 Maps
  - [x] #1618 iiab should not install menu-defs [OSM]
  - [x] #1639 Unmenu for OSM vector maps
    - [x] iiab/iiab-admin-console#195 Unmenu
  - [x] #1643 Add download and working dirs for maps [OSM vector maps especially?]
- [ ] #1625 Move osm-vector-maps materials from d.iiab.io to GitHub
- [ ] @mir123 will work on a competitive analysis of ~10 possible collaborations, among the strongest community mapping tooling/orgs worldwide, that we should possibly be working with?
- [x] @georgejhunt Defer satellite imagery to IIAB 7.1, so UX to download+install ["continent" regions](http://iiab.net/bboxes) is very solid first?
- [x] #1644 microSD card pricing has crashed, so OSM map packs could contain continent-wide satellite data, target IIAB 7.1
- [ ] #1711 Vector Map double click unreliable
- [ ] #1726 It would be easier if map content packs did not bundle both code and data
- [x] #1728 What improvements are achievable for OSM Vector Maps on Android?
- [ ] #1739 Can Map Packs auto-display (1) size-in-GB (2) levels-of-map-zoom (3) levels-of-satellite-zoom (4) number-of-searchable-cities (5) date-of-map-pack publication? In footnote @ http://box
- [x] PRs #1823 #1824 Map Pack description + extra_description explanations for teachers [OSM]
  - [x] #1825 1m & 1km details are often visible, don't sell us short!
- [x] iiab/iiab-admin-console#255 iiab-update-map overwrites existing menu defs
- [x] #2013 Can python3-geojson be made to work, as required by OS's like Ubuntu 19.10+?
- [ ] #2107 2012 -> 2020 IIAB users want (A) reliable maps (if fast maps are not possible) (B) searchable countries/oceans/rivers/mountains [OSM]
- [X] #2186 "osm-vector-maps install breaks when no internet available and already installed"
  - [X] PRs #2199 #2201 osm-split
- [ ] #2197 OSM Install Errors: "refusing to convert from file to symlink for /library/www/html/common/assets/regions.json" & "/usr/bin/iiab-update-map: not found"
- [x] #2207 Smaller Map Pack needed for both (1) testing & (2) rapid understanding of what IIAB offers
- [ ] #2208 Proposed OSM Vector Maps Data Structures
- [x] #2350 Centralize map catalog for use by osm and admin console
  - [x] #2336 Copy won't try to overwrite another file if present [for OSM install]
- [x] https://github.com/iiab/iiab-admin-console/pull/304 Admin Console 0.4.1.1
- [ ] #2461 Maps for OSM for IIAB 7.1 do not appear to be loading correctly
  - [ ] PR #2464 More php [fix for OSM]
  - [x] PR iiab/iiab-admin-console#335 "trap errors in osm install step 3"

**Comment by holta** [comment]
Good News Matt J will looking into this in the coming week, so that a fresh set of eyes guarantees instructions are crystal clear and simplified for non-technical and (less-technical) implementers of IIAB 6.6.

Draft starting points...

- Paragraph 3: https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes
- README: https://github.com/iiab/iiab-factory/blob/master/content/vector-tiles/README.md
- Download one-OR-the-other: http://download.iiab.io/content/OSM/vector-tiles/

**Comment by holta** [comment]
Matt J & I want to make this cleanly understandable, so everyday implementers can support themselves.

Here's a small start in that direction: #1033, iiab/iiab-factory#39

**Comment by holta** [comment]
Of course few read anything (nevermind RTFM!) as they used to in the lazy era of "just Google it", so we strive for a crisp/clean UX, allowing folks to support themselves wherever possible~

STILL: implementer docs are still sometimes nec (and indexed by Google!) so Matt J offers this as a model/example &mdash; what we should strive for:

> digital ocean really got things right trying to distill down technical stuff and provide how-tos for all levels of experience. one example is https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-18-04-quickstart

And:

> linode always has great examples of this as well. here's a similar tutorial of theirs compared to DO's. 
https://www.linode.com/docs/web-servers/lemp/how-to-install-a-lemp-server-on-ubuntu-18-04/

**Comment by holta** [comment]
We really need someone to share @georgejhunt's big step forward[*] at https://2018.stateofthemap.us in Detroit October 5-7.

And learn from others there what next steps make most sense for the coming decade.  Please see the program here: https://2018.stateofthemap.us/program/

The best would be if @georgejhunt attended himself.  But if nobody else is available I can try to make the trip, which won't be easy, but possibly with @mapmeld's assistance we can re-establish the technical/community connections we need to move forward broadly with authentic community mapping.

[*] offline vector maps that are customizable for every country/continent/etc, now documented as part of Internet-in-a-Box at [FAQ.IIAB.IO Question 29](http://FAQ.IIAB.IO#What_can_I_do_with_E-books_and_Internet-in-a-Box.3F)

**Comment by arky** [comment]
@holta I think a lightning talk would be apt if someone could make it.  Let me know if you need some help I usually lend a hand with communication and outreach of SOTM events

**Comment by georgejhunt** [comment]
This will probably be useful to me. I'd like to find someone who knows
about tweaking the style so that there is less overlap of detailed
information at zoom levels approaching, but not yet at,  the max zoom.

I plan to attend.

**Comment by holta** [comment]
@georgejhunt wrote:
> I plan to attend.

That would be INCREDIBLE.  I'll try to attend Detroit's https://2018.stateofthemap.us too (Fri Oct 5 - Sunday Oct 7) hoping @mapmeld and @tim-moody might consider also?

Great opportunity to catch up with NRiddle when on location there, and a close friend who recently started as a professor at UMich (Ann Arbor is ~30 min away).

**Comment by holta** [comment]
"Call for local community lightning talks, and more workshops, at State of the Map US" (in Detroit)
https://www.openstreetmap.us/2018/08/community-call/

From OSM US's blog: https://www.openstreetmap.us/blog/

**Comment by holta** [comment]
> "Call for local community lightning talks, and more workshops, at State of the Map US" (in Detroit)
https://www.openstreetmap.us/2018/08/community-call/

"The call is open until September 7." but we are only hours after the deadline so, we should submit for a lightning talk regardless, as they'll likely approve &mdash; and @arky who knows them might be able to help us out getting a place on the event's program!

**Comment by holta** [comment]
As part of https://github.com/iiab/iiab-factory/pull/51, I just now updated http://download.iiab.io/content/OSM/vector-tiles/en-osm-omt-central-am.zip based on @georgejhunt's August 2018 improvements making maps fill the entire screen/browser (https://github.com/iiab/iiab/issues/1035).

It took me forever to figure out that zip requires the `-y` flag (as well as the `-r` flag of course) to avoid including duplicate copies of every .mbtiles files (due to symlinks) but at last [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) is now ready to ship at long last!

Documentation revised hereunder, to save the next person all the agony I just went through:
https://github.com/iiab/iiab-factory/blob/master/content/vector-tiles/README.md

This is definitely sufficient for IIAB 6.6's release now, so I'm moving this ticket to IIAB 6.7.

_PS these vector maps can however be very slow to render :-(  The fonts especially (street names etc) take a while to appear on screen.  @georgejhunt we need to investigate this in person in [Detroit](http://2018.stateofthemap.us/), to bring this under control in coming years!_

**Comment by holta** [comment]
@georgejhunt is continuing to making headway on https://github.com/iiab/iiab-factory/pull/52/ "Merge non-overlapping OSM .mbtiles regions (into a single .mbtiles file)"

**Comment by holta** [comment]
Packaging of OSM is *dramatically* improved as of IIAB 7.0 to be released very shortly now, far and away more approachable than any other release to date!

Thank you @georgejhunt.  With assistance from @tim-moody 

(Of course implementer UX's are inherently hard, so the above checklist remains useful to track diverse options that might be considered for IIAB 7.1 and 7.2...)

**Comment by jvonau** [comment]
in place
