### ISSUE TITLE
Recruit someone to test IIAB on Debian 9 & 10

### ISSUE THREAD

**Issue by holta** [iiab/iiab#878]
[IIAB 6.6 pre-releases](http://download.iiab.io/6.6) are well tested on Raspbian & Ubuntu 18.04, but this is not the case with [Debian 9](https://www.debian.org/distrib/).

@arky & All: can you help find someone to install/test Internet-in-a-Box on Debian 9.4+ on x86_64 virtual machine or actual hardware?

Any body who can help test [[Debian 9.5](https://www.debian.org/News/2018/20180714)] — please run http://download.iiab.io/6.6 to check if the 12+ issues below are resolved or close:

- [x] #864 [i586] Invalid Kiwix Download Link '.bz2'
  - [x] #865 [i586] Kiwix-tools-src doesn't contain bin/ directory
  - [x] #866 Kiwix for i586 and i686 - towards resolving #864 & #865
  - [x] #895 Kiwix-tools code for i586
- [x] #867 calibre-serve Service Fails to start: Missing arguments "--log" "TimeoutStartSec'
- [x] #869 Sugarizer.service: Failed to parse output specifier, ignoring: syslog
  - [x] #899 Enable Debian 9 rsyslog service
- [x] #880 Install script [sometimes] fails to create /opt/iiab/downloads folder
- [x] 2018-07-15 http://download.iiab.io/6.6/load-big.txt tested on [Debian 9.5](https://www.debian.org/News/2018/20180714)
- [x] #902 [Debian 10] Ansible reports os_ver as "OS_not_supported"
  - [x] #904 [Debian 10] [Fixes #902] Generate correct os_ver for Debian 10/Buster Release
- [x] #928 & PR #1386 Update "php_version: 7.1" to 7.3 (& PostgreSQL 10 to 11) in debian-10.yml if mcrypt solved?
- [x] #935 [Debian 10] kalite-serve.service fails to start
- [x] #1386 Fixes for 2019's Debian 10 "Buster" + 3 outstanding issues incl workarounds
  - [ ] #1387 Debian 10 Buster: 3 outstanding issues w/ workarounds + 2 bugs (Kolibri & MongoDB)

CONVERSELY: if a volunteer if not forthcoming, we can move Debian to "secondarily" supported @ https://github.com/iiab/iiab/wiki/IIAB-Platforms (similar to Ubuntu 16.04 LTS, which is now beginning to fade in popularity).

**Comment by holta** [comment]
Any body who can help test Debian 9 — please run http://download.iiab.io/6.6 to check if the 3 issues below are ongoing:

#865 [i586] Kiwix-tools-src doesn't contain bin/ directory
#867 calibre-serve Service Fails to start: Missing arguments "--log" "TimeoutStartSec'
#869 Sugarizer.service: Failed to parse output specifier, ignoring: syslog

**Comment by holta** [comment]
While [IIAB 6.6/master](http://download.iiab.io/6.6/) works well on Debian "Stretch" 9.4 (largely due to Debian 9's libraries/dependencies being years old compared to Raspbian & Ubuntu 18.04 ;) we need someone to test [Debian 9.5](https://lists.debian.org/debian-stable-announce/2018/07/msg00000.html) after it's released "Saturday July 14th" &mdash; that official announcement will be @ https://lists.debian.org/debian-stable-announce/ in about 5 days from now.

_Thanks all for helping here & where you can!_

**Comment by holta** [comment]
> I will test it.

Many Thanks @deldesir &mdash; testing on Debian 9.5 seems very solid (so far!) but please also consider talking to @arky about testing Debian 10 if you can!

**Comment by deldesir** [comment]
No problem @holta. Possible to provide feedback for both of them (on actual hardware only). Let's tackle this together @arky.

**Comment by deldesir** [comment]
@arky Is http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/current/i386/iso-cd/debian-testing-i386-netinst.iso the best one to go with?

I am also wondering what the single number at the end of the packages' name mean from http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/.

**Comment by holta** [comment]
@arky & @deldesir doesn't http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/current/amd64/iso-cd/debian-testing-amd64-netinst.iso look better to test Debian 10 pre-releases on modern 64-bit hardware and VMs?

**Comment by holta** [comment]
> @arky & @deldesir doesn't http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/current/amd64/iso-cd/debian-testing-amd64-netinst.iso look better to test Debian 10 pre-releases on modern 64-bit hardware and VMs?

@arky & @deldesir please if you can provide an update of IIAB-on-Debian-10 in coming days (testing branch or unstable branch!) so we can finalize IIAB 6.6 Release Candidate(s) in a way that encourages others to give this a try!

(Ideally we can then raise the profile of Debian 10 on https://github.com/iiab/iiab/wiki/IIAB-Platforms on IIAB 6.6 final release early in August possibly?)

**Comment by holta** [comment]
@deldesir are there any updates on Debian 10?

(Now would be a really good time as we approach [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) final release :-)

**Comment by holta** [comment]
@deldesir it's the final days of [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) before release, and we could really use your help this week testing [IIAB 6.6/master](http://download.iiab.io/6.6/) on any version Debian 10!

(Whether the testing branch, or the unstable branch of Debian 10, just specify which one you choose to test!)

**Comment by arky** [comment]
Adding this for task list for #1055

**Comment by holta** [comment]
@deldesir, @floydianslips & @arky if you can help find someone to test http://d.iiab.io/6.7 on Debian 10 (any daily release of Buster or Sid?) prior to our release in coming weeks that'd be really great!

**Comment by floydianslips** [comment]
Just install on Debian 9.6 with no errors on first go. Will try to find time for 10.

**Comment by holta** [comment]
> Just install on Debian 9.6 with no errors on first go. Will try to find time for 10.

Amazing.  Will you use Debian 10 / Buster's `testing` branch presumably?

(FWIW @arky uses Debian Sid's `unstable` branch, which is even more bleeding-edge ;)

**Comment by holta** [comment]
> use Debian 10 / Buster's `testing` branch presumably?
> 
> (FWIW @arky uses Debian Sid's `unstable` branch, which is even more bleeding-edge ;)

@deldesir are you able to test http://d.iiab.io/6.7 on either Debian 10 above?

In anticipation of IIAB 6.7's final release later this January 2019 !

PS Debian 10 Alpha 4 was just released 2018-12-15 if you prefer :)
https://www.debian.org/devel/debian-installer/

**Comment by holta** [comment]
Thanks all for keeping on Debian 10 "Buster" pre-releases, i.e. testing http://d.iiab.io there, as its final release is now approaching fast!

(Though IIAB 7.0 might well come first, likely around early June or so!)

**Comment by holta** [comment]
Closing in favor of #1737 !
