### ISSUE TITLE
Sugarizer 1.0.1 -> 1.1 -> 1.2 -> ... Release Polish

### ISSUE THREAD

**Issue by holta** [iiab/iiab#974]
Highest Priority Sugarizer 1.0 -> 1.0.1 issues from the ~23 at https://github.com/iiab/iiab/pull/888#issuecomment-404370082 and the ~4 at https://github.com/iiab/iiab/issues/798#issuecomment-405609004) :

- [x] PR #851, #898 Fix http://box/sugarizer (worked with Sugarizer 0.7, 0.8, 0.9)
- [x] #899 Enable (or mitigate!) Debian 9 rsyslog service ?
- [ ] #915 Yank power from MongoDB and see if Sugarizer 1.0 works on next boot(s) 
- [x] #921 Optimize Sugarizer disk footprint/speed by "50%" using grunt ?
- [x] #254 Losing almost 1GB is serious on RPi (it only grabs 200-300MB on others OS's).  Still: close #254 if truly nothing can be done?
- [x] Pick & [document a trigger file](http://wiki.laptop.org/go/IIAB/FAQ#Can_I_upgrade_or_reinstall_server_apps.3F) (in the past this was /library/www/html/sugarizer/index.html) whose deletion will cause a complete reinstall of Sugarizer 1.x including deletion of all databases and kids' personal projects/data
- [ ] Works in RPi Zero W?  Y/N
- [x] #1424 Sugarizer 1.0.1 -> 1.1.0
- [x] #1429 Validate Sugarizer Server 1.1.0 on release in/around late May 2019
- [x] #1430 sugarizer v1.1.0 + sugarizer-server dev branch on Node.js 10.x
  - [x] #1431 Node-RED fails on Ubuntu Server 18.04: node-red.service.j2 needs /usr/bin/node-red-pi NOT /usr/local/bin
    - [x] #1432 Node-RED service fix #1431...for Ubuntu Server 18.04 & other OS's too? [included in PR #1430]
- [x] #1966 Sugarizer 1.1 -> 1.2 2019-09-26
- [ ] Consider a Docker container if truly necessary, including Node.js & MongoDB?

**Comment by jvonau** [comment]
Review sub issue and close stale ones.

**Comment by jvonau** [comment]
Works in RPi Zero W? Y/N is a FAQ and docker is out close.

**Comment by holta** [comment]
I don't know if Sugarizer works on RPi Zero W.

**Comment by jvonau** [comment]
it's subject to the nodejs version notes about arm6l and manual steps/rollback, or just own up and say UN-supported on arm6l.

**Comment by jvonau** [comment]
#2739

**Comment by jvonau** [comment]
#915 is closed, the rest is stale.

**Comment by holta** [comment]
Good enough, 4 years later (as lot of work has gone into this!!)
