### ISSUE TITLE
Kolibri 0.10.2+ Release Polish

### ISSUE THREAD

**Issue by holta** [iiab/iiab#977]
Highest priorities to bring Kolibri into the hands of mainstream teachers: (building off @arky's foundational July 2018 PR's listed in https://github.com/iiab/iiab/issues/841#issuecomment-405767755)

- [x] #1076 Should the [pip install of Kolibri](https://github.com/iiab/iiab/blob/master/roles/kolibri/tasks/main.yml#L22-L27) be confined to a virtualenv for safety?
- [x] #884 PR #1044 Automate torrenting+installing of KA Lite videos in 7 languages
- [x] #913 learningequality/kolibri#4127 learningequality/kolibri#4176 &mdash; http://box/kolibri should work! (not just http://box:8009)
- [ ] #920 pip cache memory issues; installing Kolibri, KA Lite & OSM? [WAS: Is 500MB swap file best on RPi?]
- [x] #938 Kolibri pip (re)install intermittently fails on RPi
- [x] #922 Verify Kolibri 0.10.0 -> 0.10.1 -> 0.10.2 -> 0.10.3 or 0.11.0 ?
- [x] #1094 Kolibri did not start within 2MIN timeout during BIG install on RPi 3
- [x] #1108 Use Handlers for Kolibri Services
- [x] #1109 Clean up RedirectMatch rules
- [x] #1110 Test Kolibri 0.11.0+ (for Kolibri & others?)
- [ ] Understand why Kolibri appears slow on RPi?
- [ ] Understand why memory consumption can be very high on RPi!  [@jvonau report on 2018-09-01]
- [ ] _Friendly guidance on integrating Other Content (@ivanistheone will record the video ;)_
- [ ] #1545 Close out this entire checklist (see 1545 which is a new checklist for [IIAB 7.0](https://github.com/iiab/iiab/milestone/5) !)

**Comment by arky** [comment]
Requested kolibri developers to release development pip packages to enable testing. 

https://github.com/learningequality/kolibri/issues/4218

**Comment by holta** [comment]
Please follow up on our new Kolibri checklist here:

https://github.com/iiab/iiab/issues/1545
