### ISSUE TITLE
Enable local_vars.yml to set /etc/iiab/openvpn_handle during IIAB installation

### ISSUE THREAD

**Issue by holta** [iiab/iiab#995]
Implementers want uninterrupted installs (or at least as streamlined as possible).

So prescribing /etc/iiab/handle in advance within /etc/iiab/local_vars.yml would allow this to happen, regardless whether local_vars.yml is constructed interactively by a sexy install, or more traditionally using a text editor like nano!

Related:
- [x] #317 Install OpenVPN/TeamViewer/support tool(s) BEFORE installs begin [or near the very beginning!] 
- [ ] #872 Reboot + Auto-Continue...IIAB Install Scripts (for OS updates etc)
- [ ] #958 Non-ASCII Characters in install.txt Bash Script
- [ ] #963, https://github.com/iiab/iiab-factory/pull/33 Host install.txt on Github
- [ ] #994 Should IIAB support NOOBS to broaden participation?
- [x] PRs #996, #997, #998, #1000, #1001, #1003, #1004 making the [openvpn playbook/role](https://github.com/iiab/iiab/tree/master/roles/openvpn) more readable, while implementing variable openvpn_handle

_**[ CHECKLIST ABOVE HAS NOW MOVED TO IIAB 6.7 TICKET #1028 ]**_
